import { Skin_Care_Product } from "./data-types";

export const sample_products: Skin_Care_Product[] = [
    {
        id: '1',
        name: 'Crebeau Placenta Pearl Refreshing Toner',
        price: '34.99',
        imageUrl: 'assets/img/Products/p-1.png',
        skinType: '',
        spf: '',
        Conscious: '',
        brand: 'Crebeau',
        item_form: 'Liquid',
        item_volume: '150 ml',
        type_Product:'skin',
        discription: 'Soothes irritated skin after cleansing and regulates oil/moisture.Patented ingredients can have a soothing effect on the skin.'
       
    },
    {
        id: '2',
        name: 'Crebeau Placenta Pearl Moisturizing Emulsion',
        price: '34.99',
        imageUrl: 'assets/img/Products/p-2.png',
        skinType: '',
        spf: '',
        Conscious: '',
        brand: 'Crebeau',
        item_form: 'Liquid',
        item_volume: '150 ml',
        type_Product:'skin',
        discription: 'It is an essence-type emulsionthat helps maintainthe optimal oil-moisture balance by delivering a fresh feeling of moistureand oil absorbed into the skin the momentit is applied.'
    },
    {
        id: '3',
        name: 'Crebeau Placenta Pearl Repair Eye Cream',
        price: '34.99',
        imageUrl: 'assets/img/Products/p3.png',
        skinType: 'Sensitive',
        spf: '',
        Conscious: '',
        brand: '',
        item_form: '',
        item_volume: '',
        type_Product:'skin',
        discription: ''
    },
    {
        id: '4',
        name: 'Crebeau Placenta Pearl Moisturizing Night Cream',
        price: '34.99',
        imageUrl: 'assets/img/Products/p4.png',
        skinType: 'Sensitive',
        spf: '',
        Conscious: 'vegan',
        brand: 'Crebeau',
        item_form: 'Cream',
        item_volume: '50 g',
        type_Product:'skin',
        discription: 'It increases the density of the skin cell tissue, resulting in a good effect on wrinkle improvement and elasticity enhancement.'
    },
    {
        id: '5',
        name: 'Crebeau Placenta Pearl Water Active Cream',
        price: '34.99',
        imageUrl: 'assets/img/Products/p5.png',
        skinType: 'dry',
        spf: 'below15',
        Conscious: '',
        brand: 'Crebeau',
        item_form: 'Cream',
        item_volume: '50 g',
        type_Product:'skin',
        discription: 'It is a velvet-like cream that adds moisture to make your skin comfortable and clear.'
    },
    {
        id: '6',
        name: 'Crebeau Air Cushion (including refills)',
        price: '34.99',
        imageUrl: 'assets/img/Products/p-6.png',
        skinType: 'Sensitive',
        spf: '',
        Conscious: '',
        brand: 'Crebeau',
        item_form: 'Cream',
        item_volume: '13g',
        type_Product:'skin',
        discription: 'Triple functional cosmetics for whitening, wrinkle smoothing and UV protection.'
    },
    {
        id: '7',
        name: 'Cover Story P.S.A Four Facial Tightening Masks',
        price: '34.99',
        imageUrl: 'assets/img/Products/p7.png',
        skinType: '',
        spf: 'below15',
        Conscious: 'vegan',
        brand: 'Crebeau',
        item_form: 'Cream',
        item_volume: '130 g',
        type_Product:'skin',
        discription: 'Four patented peptide ingredients and CoQ10 ingredient, which is more effective than vitamin C, promote skin cell regeneration &proliferation.. it gives vitality with a good effect, makes the skin lively, & makes the skin firm and elastic.'
    },
    {
        id: '8',
        name: 'Crebeau Placenta Pearl Moisturizing Hyaluron Ampoule',
        price: '34.99',
        imageUrl: 'assets/img/Products/p8.jpg',
        skinType: 'Sensitive',
        spf: '',
        Conscious: '',
        brand: 'Crebeau',
        item_form: 'Liquid',
        item_volume: '30g',
        type_Product:'skin',
        discription: 'Skin dryness has a great effect on wrinkle formation. This ampoule is composed of sodium hyaluronate as the main base, so when the skin needs moisture, it instantly relieves skin dryness through instant penetration.'
    },
    {
        id: '9',
        name: 'Crebeau Placenta Pearl Moisturizing Whiteing Ampoule',
        price: '34.99',
        imageUrl: 'assets/img/Products/p-9.png',
        skinType: 'dry',
        spf: 'below15',
        Conscious: 'vegan',
        brand: 'Crebeau',
        item_form: 'Liquid',
        item_volume: '30g',
        type_Product:'skin',
        discription: ' Various flower extracts when your skin feels dull due to accumulated fatigue or tired daily life. It clears the skin tone and returns it to a bright skin condition.'
    },
    {
        id: '10',
        name: 'Crebeau Placenta Pearl Moisturizing Collagen Ampoule',
        price: '34.99',
        imageUrl: 'assets/img/Products/p-10.png',
        skinType: 'dry',
        spf: '',
        Conscious: '',
        brand: 'Crebeau',
        item_form: 'Liquid',
        item_volume: '30g',
        type_Product:'skin',
        discription: '9 types of flowerand herb extractsare added to the base and collagen is added to improve the skin texture and strengthen the skin barrier to help prevent skin damage and relieve dryness to help moisturize and strengthen skin elasticity.'
    },
    {
        id: '11',
        name: 'Crebeau Placenta Pearl Purifying Foam Cleansing',
        price: '34.99',
        imageUrl: 'assets/img/Products/p-11.png',
        skinType: '',
        spf: '',
        Conscious: 'vegan',
        brand: 'Crebeau',
        item_form: 'Liquid',
        item_volume: '100ml',
        type_Product:'skin',
        discription: 'It cleans the skin of impurities with a soft foam and leaves the skin moist and clear even after washing the face.'
    },
    {
        id: '12',
        name: 'Crebeau Bb Cream (Tube Type)',
        price: '34.99',
        imageUrl: 'assets/img/Products/P-12.png',
        skinType: '',
        spf: 'below15',
        Conscious: '',
        brand: '',
        item_form: '',
        item_volume: '',
        type_Product:'skin',
        discription: ''
    },
    {
        id: '13',
        name: 'Multi-bom stic',
        price: '34.99',
        imageUrl: 'assets/img/Products/p13.jpg',
        skinType: '',
        spf: '',
        Conscious: '',
        brand: '',
        item_form: '',
        item_volume: '',
        type_Product:'skin',
        discription: ''
    },
    {
        id: '14',
        name: 'Guerisson 9 Complex Cream',
        price: '34.99',
        imageUrl: 'assets/img/Products/p19.jpg',
        skinType: '',
        spf: 'below15',
        Conscious: '',
        brand: 'Guerisson',
        item_form: 'Cream',
        item_volume: '30g',
        type_Product:'skin',
        discription: 'A highly soluble and conditioning ingredient free from steroids and preservatives to replenish lost moisture and then lock it in for an immediate hydrating effect. Antioxidant rich cream is mild enough to use even on the most delicate of skins.'
    }

]